import { mysqlSchema } from "../adapters/mysql-schema";
import { DEFAULT_PREFIX } from "../adapters/sql-shared";

export type Language = "ts" | "js";
export type ModuleFormat = "esm" | "cjs";

export interface StarterOptions {
  language: Language;
  format: ModuleFormat;
  prefix: string;
}

// Generated files always use "\n"; git and editors handle it on every platform.

export function migrationSql(prefix: string, version: string): string {
  return [
    `-- permly schema (MySQL / MariaDB), generated by permly ${version}.`,
    `-- Creates 5 tables prefixed "${prefix}". Safe to run more than once: existing tables are`,
    `-- left untouched. Equivalent to running \`npx permly migrate${prefix === DEFAULT_PREFIX ? "" : ` --prefix ${prefix}`}\`.`,
    "",
    mysqlSchema(prefix),
  ].join("\n");
}

const PERMISSIONS = `["posts.create", "posts.edit", "posts.edit.own", "posts.delete"]`;
const ROLES = `["admin", "editor", "viewer"]`;

export function starterFile({ language, format, prefix }: StarterOptions): string {
  const esm = language === "ts" || format === "esm";
  const adapterOptions = prefix === DEFAULT_PREFIX ? "" : `, { prefix: "${prefix}" }`;
  const exportConst = esm ? "export const" : "const";
  const exportFunction = esm ? "export async function" : "async function";
  const returnType = language === "ts" ? ": Promise<void>" : "";
  const imports = esm
    ? [
        `import { createPool } from "mysql2/promise";`,
        `import { createPermissions } from "permly";`,
        `import { mysqlAdapter } from "permly/mysql";`,
      ]
    : [
        `const { createPool } = require("mysql2/promise");`,
        `const { createPermissions } = require("permly");`,
        `const { mysqlAdapter } = require("permly/mysql");`,
      ];
  const expressImport = esm
    ? `import { permlyExpress } from "permly/express";`
    : `const { permlyExpress } = require("permly/express");`;
  const namesComment =
    language === "ts"
      ? "  // Every permission and role your app uses. Names autocomplete, and typos don't compile."
      : "  // Every permission and role your app uses.";

  return `// Roles & permissions for this app. Generated by \`npx permly init\`; edit freely.
${imports.join("\n")}

const url = process.env.DATABASE_URL;
if (!url) {
  throw new Error("Set DATABASE_URL, e.g. mysql://user:password@localhost:3306/mydb");
}

${exportConst} perms = createPermissions({
  adapter: mysqlAdapter(createPool(url)${adapterOptions}),
${namesComment}
  permissions: ${PERMISSIONS},
  roles: ${ROLES},
});

/**
 * Call once at startup, before handling requests. Creates the roles and permissions above if
 * they're missing, then grants the defaults below. Safe to run on every start.
 */
${exportFunction} setupPermissions()${returnType} {
  await perms.sync();
  await perms.role("admin").givePermission("*");
  await perms.role("editor").givePermission("posts.create", "posts.edit.own");
}
${esm ? "" : "\nmodule.exports = { perms, setupPermissions };\n"}
// Give users roles, e.g. at sign-up:
//   await perms.user(user.id).assignRole("editor");
//
// Check anywhere:
//   if (await perms.user(user.id).can("posts.create")) { ... }
//
// Protect Express routes (reads req.user.id by default):
//   ${expressImport}
//   const guard = permlyExpress(perms);
//   app.post("/posts", guard.permission("posts.create"), createPost);
//   app.put(
//     "/posts/:id",
//     guard.own("posts.edit", async (req) => (await findPost(req.params.id))?.userId),
//     updatePost,
//   );
`;
}
