import { mysqlSchema } from "../adapters/mysql-schema";
import { postgresSchema } from "../adapters/postgres-schema";
import { DEFAULT_PREFIX, DEFAULT_SCHEMA } from "../adapters/sql-shared";

export type Database = "mysql" | "postgres";
export type Language = "ts" | "js";
export type ModuleFormat = "esm" | "cjs";

export interface StarterOptions {
  db: Database;
  language: Language;
  format: ModuleFormat;
  prefix: string;
  schema: string;
}

/** Everything that differs between databases in the generated files and messages. */
export const DRIVERS: Record<
  Database,
  { label: string; driver: string; adapter: string; urlExample: string }
> = {
  mysql: {
    label: "MySQL / MariaDB",
    driver: "mysql2",
    adapter: "mysqlAdapter",
    urlExample: "mysql://user:password@localhost:3306/mydb",
  },
  postgres: {
    label: "Postgres",
    driver: "pg",
    adapter: "postgresAdapter",
    urlExample: "postgres://user:password@localhost:5432/mydb",
  },
};

// Generated files always use "\n"; git and editors handle it on every platform.

export function migrationSql(
  db: Database,
  prefix: string,
  schema: string,
  version: string,
): string {
  const flags = [
    db === "postgres" ? " --db postgres" : "",
    prefix === DEFAULT_PREFIX ? "" : ` --prefix ${prefix}`,
    db === "postgres" && schema !== DEFAULT_SCHEMA ? ` --schema ${schema}` : "",
  ].join("");
  const where = db === "postgres" ? ` in schema "${schema}" (which must already exist)` : "";
  return [
    `-- permly schema (${DRIVERS[db].label}), generated by permly ${version}.`,
    `-- Creates 5 tables prefixed "${prefix}"${where}. Safe to run more than once: existing`,
    `-- tables are left untouched. Equivalent to running \`npx permly migrate${flags}\`.`,
    "",
    db === "postgres" ? postgresSchema(prefix, schema) : mysqlSchema(prefix),
  ].join("\n");
}

const PERMISSIONS = `["posts.create", "posts.edit", "posts.edit.own", "posts.delete"]`;
const ROLES = `["admin", "editor", "viewer"]`;

export function starterFile({ db, language, format, prefix, schema }: StarterOptions): string {
  const esm = language === "ts" || format === "esm";
  const { adapter, urlExample } = DRIVERS[db];

  const options = [
    prefix === DEFAULT_PREFIX ? "" : `prefix: "${prefix}"`,
    db === "postgres" && schema !== DEFAULT_SCHEMA ? `schema: "${schema}"` : "",
  ].filter(Boolean);
  const adapterOptions = options.length > 0 ? `, { ${options.join(", ")} }` : "";

  const driverImport =
    db === "postgres"
      ? esm
        ? `import pg from "pg";`
        : `const { Pool } = require("pg");`
      : esm
        ? `import { createPool } from "mysql2/promise";`
        : `const { createPool } = require("mysql2/promise");`;
  const pool =
    db === "postgres"
      ? `new ${esm ? "pg." : ""}Pool({ connectionString: url })`
      : "createPool(url)";
  const imports = esm
    ? [
        driverImport,
        `import { createPermissions } from "permly";`,
        `import { ${adapter} } from "permly/${db}";`,
      ]
    : [
        driverImport,
        `const { createPermissions } = require("permly");`,
        `const { ${adapter} } = require("permly/${db}");`,
      ];
  const expressImport = esm
    ? `import { permlyExpress } from "permly/express";`
    : `const { permlyExpress } = require("permly/express");`;
  const exportConst = esm ? "export const" : "const";
  const exportFunction = esm ? "export async function" : "async function";
  const returnType = language === "ts" ? ": Promise<void>" : "";
  const namesComment =
    language === "ts"
      ? "  // Every permission and role your app uses. Names autocomplete, and typos don't compile."
      : "  // Every permission and role your app uses.";

  return `// Roles & permissions for this app. Generated by \`npx permly init\`; edit freely.
${imports.join("\n")}

const url = process.env.DATABASE_URL;
if (!url) {
  throw new Error("Set DATABASE_URL, e.g. ${urlExample}");
}

${exportConst} perms = createPermissions({
  adapter: ${adapter}(${pool}${adapterOptions}),
${namesComment}
  permissions: ${PERMISSIONS},
  roles: ${ROLES},
});

/**
 * Call once at startup, before handling requests. Safe to run on every start.
 *
 * sync() creates the roles and permissions above if they're missing. The default grants
 * below are only applied to roles that sync() has just created, i.e. on first setup.
 * After that, the database is the source of truth: permission changes made later (by an
 * admin, a script, ...) are kept across restarts, never reset to these defaults.
 */
${exportFunction} setupPermissions()${returnType} {
  const { createdRoles } = await perms.sync();
  if (createdRoles.includes("admin")) {
    await perms.role("admin").givePermission("*");
  }
  if (createdRoles.includes("editor")) {
    await perms.role("editor").givePermission("posts.create", "posts.edit.own");
  }
}
${esm ? "" : "\nmodule.exports = { perms, setupPermissions };\n"}
// Give users roles, e.g. at sign-up:
//   await perms.user(user.id).assignRole("editor");
//
// Check anywhere:
//   if (await perms.user(user.id).can("posts.create")) { ... }
//
// Protect Express routes (reads req.user.id by default):
//   ${expressImport}
//   const guard = permlyExpress(perms);
//   app.post("/posts", guard.permission("posts.create"), createPost);
//   app.put(
//     "/posts/:id",
//     guard.own("posts.edit", async (req) => (await findPost(req.params.id))?.userId),
//     updatePost,
//   );
`;
}
