import { mongodbSetup } from "../adapters/mongodb-setup";
import { mysqlSchema } from "../adapters/mysql-schema";
import { postgresSchema } from "../adapters/postgres-schema";
import { DEFAULT_PREFIX, DEFAULT_SCHEMA } from "../adapters/sql-shared";
import type { Database } from "./args";

export type { Database } from "./args";
export type Language = "ts" | "js";
export type ModuleFormat = "esm" | "cjs";
/** For MongoDB: the app's own mongoose connection, or the native driver. */
export type MongoStyle = "mongoose" | "native";

export interface StarterOptions {
  db: Database;
  language: Language;
  format: ModuleFormat;
  prefix: string;
  schema: string;
  mongoStyle: MongoStyle;
}

/** Everything that differs between databases in the generated files and messages. */
export const DRIVERS: Record<
  Database,
  { label: string; driver: string; adapter: string; urlExample: string }
> = {
  mysql: {
    label: "MySQL / MariaDB",
    driver: "mysql2",
    adapter: "mysqlAdapter",
    urlExample: "mysql://user:password@localhost:3306/mydb",
  },
  postgres: {
    label: "Postgres",
    driver: "pg",
    adapter: "postgresAdapter",
    urlExample: "postgres://user:password@localhost:5432/mydb",
  },
  mongodb: {
    label: "MongoDB",
    driver: "mongodb",
    adapter: "mongodbAdapter",
    urlExample: "mongodb://user:password@localhost:27017/mydb",
  },
};

// Generated files always use "\n"; git and editors handle it on every platform.

/** The migration file: SQL for MySQL/Postgres, a Node script for MongoDB. */
export function migrationFile(
  db: Database,
  prefix: string,
  schema: string,
  version: string,
): { extension: "sql" | "mjs"; content: string } {
  if (db === "mongodb") return { extension: "mjs", content: mongodbScript(prefix, version) };
  const flags = [
    db === "postgres" ? " --db postgres" : "",
    prefix === DEFAULT_PREFIX ? "" : ` --prefix ${prefix}`,
    db === "postgres" && schema !== DEFAULT_SCHEMA ? ` --schema ${schema}` : "",
  ].join("");
  const where = db === "postgres" ? ` in schema "${schema}" (which must already exist)` : "";
  const content = [
    `-- permly schema (${DRIVERS[db].label}), generated by permly ${version}.`,
    `-- Creates 5 tables prefixed "${prefix}"${where}. Safe to run more than once: existing`,
    `-- tables are left untouched. Equivalent to running \`npx permly migrate${flags}\`.`,
    "",
    db === "postgres" ? postgresSchema(prefix, schema) : mysqlSchema(prefix),
  ].join("\n");
  return { extension: "sql", content };
}

function mongodbScript(prefix: string, version: string): string {
  const flag = prefix === DEFAULT_PREFIX ? "" : ` --prefix ${prefix}`;
  const collections = JSON.stringify(mongodbSetup(prefix), null, 2);
  return `// permly collections and indexes (MongoDB), generated by permly ${version}.
// Creates what's missing; existing collections and indexes are left untouched, so it is safe
// to run more than once. Same as \`npx permly migrate${flag}\`. Run it with:
//
//   DATABASE_URL=${DRIVERS.mongodb.urlExample} node <this file>
//
// Uses the "mongodb" driver, or the one inside "mongoose", whichever your project has.

const collections = ${collections};

async function loadMongoClient() {
  try {
    return (await import("mongodb")).MongoClient;
  } catch {
    return (await import("mongoose")).default.mongo.MongoClient;
  }
}

const url = process.env.DATABASE_URL;
if (!url) {
  console.error("Set DATABASE_URL, e.g. ${DRIVERS.mongodb.urlExample}");
  process.exit(1);
}

const MongoClient = await loadMongoClient();
const client = new MongoClient(url);
try {
  const db = client.db();
  const existing = new Set(
    (await db.listCollections({}, { nameOnly: true }).toArray()).map((c) => c.name),
  );
  for (const { name, indexes } of collections) {
    if (!existing.has(name)) {
      await db.createCollection(name).catch((error) => {
        if (error.code !== 48) throw error; // created meanwhile by someone else
      });
    }
    await db.collection(name).createIndexes(indexes);
    console.log(\`\${existing.has(name) ? "exists " : "created"}  \${name}\`);
  }
} finally {
  await client.close();
}
`;
}

const PERMISSIONS = `["posts.create", "posts.edit", "posts.edit.own", "posts.delete"]`;
const ROLES = `["admin", "editor", "viewer"]`;

interface DriverCode {
  imports: string[];
  /** Lines before `createPermissions`, e.g. reading DATABASE_URL. */
  setup: string;
  /** The adapter argument expression. */
  handle: string;
  /** Extra sentence for the setupPermissions() comment. */
  note: string;
}

function driverCode(options: StarterOptions, esm: boolean): DriverCode {
  const { db, mongoStyle } = options;
  const { urlExample } = DRIVERS[db];
  const readUrl = `const url = process.env.DATABASE_URL;
if (!url) {
  throw new Error("Set DATABASE_URL, e.g. ${urlExample}");
}
`;
  const importFrom = (names: string, module: string, defaultImport = false) =>
    esm
      ? defaultImport
        ? `import ${names} from "${module}";`
        : `import { ${names} } from "${module}";`
      : defaultImport
        ? `const ${names} = require("${module}");`
        : `const { ${names} } = require("${module}");`;

  if (db === "mysql") {
    return {
      imports: [importFrom("createPool", "mysql2/promise")],
      setup: readUrl,
      handle: "createPool(url)",
      note: "",
    };
  }
  if (db === "postgres") {
    return {
      imports: [esm ? `import pg from "pg";` : `const { Pool } = require("pg");`],
      setup: readUrl,
      handle: `new ${esm ? "pg." : ""}Pool({ connectionString: url })`,
      note: "",
    };
  }
  if (mongoStyle === "mongoose") {
    return {
      imports: [importFrom("mongoose", "mongoose", true)],
      setup: "",
      handle: "mongoose",
      note: "\n * Uses your app's mongoose connection: call it after `await mongoose.connect(url)`.",
    };
  }
  return {
    imports: [importFrom("MongoClient", "mongodb")],
    setup: `${readUrl}
// Connects on first use. client.db() is the database named in the URL.
const client = new MongoClient(url);
`,
    handle: "client.db()",
    note: "",
  };
}

export function starterFile(options: StarterOptions): string {
  const { db, language, format, prefix, schema } = options;
  const esm = language === "ts" || format === "esm";
  const { adapter } = DRIVERS[db];
  const code = driverCode(options, esm);

  const adapterOptions = [
    prefix === DEFAULT_PREFIX ? "" : `prefix: "${prefix}"`,
    db === "postgres" && schema !== DEFAULT_SCHEMA ? `schema: "${schema}"` : "",
  ].filter(Boolean);
  const optionsArg = adapterOptions.length > 0 ? `, { ${adapterOptions.join(", ")} }` : "";

  const imports = esm
    ? [
        ...code.imports,
        `import { createPermissions } from "permly";`,
        `import { ${adapter} } from "permly/${db}";`,
        language === "ts" ? `import type { InferPermission, InferRole } from "permly";` : null,
      ].filter(Boolean)
    : [
        ...code.imports,
        `const { createPermissions } = require("permly");`,
        `const { ${adapter} } = require("permly/${db}");`,
      ];
  const expressImport = esm
    ? `import { permlyExpress } from "permly/express";`
    : `const { permlyExpress } = require("permly/express");`;
  const exportConst = esm ? "export const" : "const";
  const exportFunction = esm ? "export async function" : "async function";
  const returnType = language === "ts" ? ": Promise<void>" : "";
  const namesComment =
    language === "ts"
      ? "  // Every permission and role your app uses. Names autocomplete, and typos don't compile."
      : "  // Every permission and role your app uses.";
  const typeExports =
    language === "ts"
      ? `
// Type definitions for permissions and roles in your app
export type Permission = InferPermission<typeof perms>;
export type Role = InferRole<typeof perms>;
`
      : "";

  return `// Roles & permissions for this app. Generated by \`npx permly init\`; edit freely.
${imports.join("\n")}

${code.setup}${code.setup ? "\n" : ""}${exportConst} perms = createPermissions({
  adapter: ${adapter}(${code.handle}${optionsArg}),
${namesComment}
  permissions: ${PERMISSIONS},
  roles: ${ROLES},
});${typeExports}
/**
 * Call once at startup, before handling requests. Safe to run on every start.${code.note}
 *
 * sync() creates the roles and permissions above if they're missing. The default grants
 * below are only applied to roles that sync() has just created, i.e. on first setup.
 * After that, the database is the source of truth: permission changes made later (by an
 * admin, a script, ...) are kept across restarts, never reset to these defaults.
 */
${exportFunction} setupPermissions()${returnType} {
  const { createdRoles } = await perms.sync();
  if (createdRoles.includes("admin")) {
    await perms.role("admin").givePermission("*");
  }
  if (createdRoles.includes("editor")) {
    await perms.role("editor").givePermission("posts.create", "posts.edit.own");
  }
}
${esm ? "" : "\nmodule.exports = { perms, setupPermissions };\n"}
// Give users roles, e.g. at sign-up:
//   await perms.user(user.id).assignRole("editor");
//
// Check anywhere:
//   if (await perms.user(user.id).can("posts.create")) { ... }
//
// Protect Express routes (reads req.user.id by default):
//   ${expressImport}
//   const guard = permlyExpress(perms);
//   app.post("/posts", guard.permission("posts.create"), createPost);
//   app.put(
//     "/posts/:id",
//     guard.own("posts.edit", async (req) => (await findPost(req.params.id))?.userId),
//     updatePost,
//   );
`;
}
